try:
	function()
except BaseException as e:    
    print e